import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";




const inter=Inter({subsets:["latin"]})

export const metadata = {
  title: "Doctors Appointment App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
     appearance={{
        baseTheme: dark,
      }}
      >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
           
          </ThemeProvider>
        <main className="min-h-screen">{children}</main>
        
            <Header />
        <footer className="bg-muted/50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-300">
            <p>
              Made with Love
            </p>
          </div>
        </footer>


      </body>
    </html>
    </ClerkProvider>
  );
}
