import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { FaFacebookF, FaTwitter, FaLinkedinIn, FaInstagram } from "react-icons/fa";



const inter=Inter({subsets:["latin"]})

export const metadata = {
  title: "Doctors Appointment App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} frontendApi={process.env.NEXT_PUBLIC_CLERK_FRONTEND_API} appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster/>


             <footer className="bg-black text-gray-300">
      <div className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-10">
        
        {/* Brand Section */}
        <div className="text-center md:text-left">
          <h2 className="text-2xl font-bold text-emerald-500">DocCare</h2>
          <p className="mt-3 text-sm text-gray-400 leading-relaxed">
            Your trusted healthcare partner. Book appointments, consult doctors, 
            and stay healthy with us.
          </p>
        </div>

        {/* Quick Links */}
        <div className="text-center md:text-left">
          <h3 className="text-lg font-semibold text-emerald-400 mb-4">Quick Links</h3>
          <ul className="space-y-2">
            {["Home", "About Us", "Services", "Contact"].map((link, i) => (
              <li key={i}>
                <a
                  href="#"
                  className="relative group transition text-gray-400"
                >
                  {link}
                  <span className="absolute left-0 -bottom-1 w-0 h-[2px] bg-emerald-500 transition-all duration-300 group-hover:w-full"></span>
                </a>
              </li>
            ))}
          </ul>
        </div>

        {/* Support */}
        <div className="text-center md:text-left">
          <h3 className="text-lg font-semibold text-emerald-400 mb-4">Support</h3>
          <ul className="space-y-2">
            {["FAQ", "Privacy Policy", "Terms & Conditions"].map((link, i) => (
              <li key={i}>
                <a
                  href="#"
                  className="relative group transition text-gray-400"
                >
                  {link}
                  <span className="absolute left-0 -bottom-1 w-0 h-[2px] bg-emerald-500 transition-all duration-300 group-hover:w-full"></span>
                </a>
              </li>
            ))}
          </ul>
        </div>

        {/* Contact */}
        <div className="text-center md:text-left">
          <h3 className="text-lg font-semibold text-emerald-400 mb-4">Contact Us</h3>
          <p className="text-sm text-gray-400">📍 Mumbai, India</p>
          <p className="text-sm text-gray-400">📞 +91 98765 43210</p>
          <p className="text-sm text-gray-400">✉️ support@doccare.com</p>

          {/* Social Icons */}
          <div className="flex justify-center md:justify-start space-x-5 mt-5">
            {[FaFacebookF, FaTwitter, FaLinkedinIn, FaInstagram].map((Icon, i) => (
              <a
                key={i}
                href="#"
                className="text-gray-400 hover:text-emerald-500 transition transform hover:scale-110 hover:drop-shadow-[0_0_8px_#10B981]"
              >
                <Icon size={20} />
              </a>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom Section */}
      <div className="border-t border-gray-700 py-5 text-center text-xs sm:text-sm text-gray-500">
        © {new Date().getFullYear()} DocCare. All rights reserved.
      </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

